// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFDy8rtWHyRWHkUyF0UdqN1uN8dilaYdA',
    appId: '1:925488522670:web:8d3f8ff613abe7ecf1d43f',
    messagingSenderId: '925488522670',
    projectId: 'qrauth-a6076',
    authDomain: 'qrauth-a6076.firebaseapp.com',
    storageBucket: 'qrauth-a6076.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB393UjI5xV26FxF6_EXZxE_5eoY21mz_U',
    appId: '1:925488522670:android:ced844d540614d25f1d43f',
    messagingSenderId: '925488522670',
    projectId: 'qrauth-a6076',
    storageBucket: 'qrauth-a6076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0vFI1sOn4Xu2kNhfCkY0C7Uk4q0XCN4',
    appId: '1:925488522670:ios:10f1600646b81d24f1d43f',
    messagingSenderId: '925488522670',
    projectId: 'qrauth-a6076',
    storageBucket: 'qrauth-a6076.firebasestorage.app',
    iosBundleId: 'com.example.qrbasedauthenication',
  );
}
